improve dev setup

diff --git a/bin/ontoportal b/bin/ontoportal
--- a/bin/ontoportal
+++ b/bin/ontoportal
@@ -3,11 +3,12 @@
 # Function to display script usage information
 show_help() {
   cat << EOL
-Usage: $0 {dev|test|run|help} [--reset-cache] [--api-url API_URL] [--api-key API_KEY] [--old-path OLD_PATH] [--goo-path GOO_PATH] [--sparql-client-path SPARQL_CLIENT_PATH] [--with-provision]
+Usage: $0 {dev|test|run|help} [--reset-cache] [--api-url API_URL] [--linked-data-path ONTOLOGIES_LINKED_DATA_PATH] [--goo-path GOO_PATH] [--sparql-client-path SPARQL_CLIENT_PATH] [--with-provision]
   dev            : Start the Ontoportal API development server.
                   Example: $0 dev --api-url http://localhost:9393
                   Use --reset-cache to remove volumes: $0 dev --reset-cache
-                  Use --with-provision to parse ontology for use
+                  Use --provision-user-only to create admin user only without ontology parsing.
+                  Use --provision-ontology to create admin user and parse ontology for use
   test           : Run tests. Specify either a test file or use 'all'.
                   Example: $0 test test/controllers/test_users_controller.rb -v --name=name_of_the_test
                   Example (run all tests): $0 test all -v
@@ -20,16 +21,16 @@ Description:
   running tests, and executing commands within the Ontoportal API Docker container.
 
 Options:
-  --reset-cache             : Remove Docker volumes (used with 'dev').
-  --with-provision          : Parse ontology for use.
-  --api-url API_URL         : Specify the API URL.
-  --api-key API_KEY         : Specify the API key.
-  --old-path OLD_PATH       : Specify the path for ontologies_linked_data.
-  --goo-path GOO_PATH       : Specify the path for goo.
-  --sparql-client-path      : Specify the path for sparql-client.
-  test_file | all           : Specify either a test file or  all the tests will be run.
-  -v                        : Enable verbosity.
-  --name=name_of_the_test   : Specify the name of the test.
+  --reset-cache                                   : Remove Docker volumes (used with 'dev').
+  --provision-user-only                           : Parse ontology for use.
+  --provision-ontology                            : Parse ontology for use.
+  --api-url API_URL                               : Specify the API URL.
+  --linked-data-path ONTOLOGIES_LINKED_DATA_PATH  : Specify the path for ontologies_linked_data.
+  --goo-path GOO_PATH                             : Specify the path for goo.
+  --sparql-client-path                            : Specify the path for sparql-client.
+  test_file | all                                 : Specify either a test file or  all the tests will be run.
+  -v                                              : Enable verbosity.
+  --name=name_of_the_test                         : Specify the name of the test.
 
 Goals:
   - Simplify common tasks related to Ontoportal API development using Docker.
@@ -38,11 +39,11 @@ EOL
 }
 
 
-# Function to update or create the .env file with API_URL and API_KEY
+# Function to update or create the .env file with API_URL
 update_env_file() {
   # Update the .env file with the provided values
   local api_url="$1"
-  local old_path="$2"
+  local linked_data_path="$2"
   local goo_path="$3"
   local sparql_client_path="$4"
 
@@ -54,7 +55,7 @@ update_env_file() {
         if [[ "$line" == "API_URL="* && -n "$api_url" ]]; then
           echo "API_URL=$api_url"
         elif [[ "$line" == "ONTOLOGIES_LINKED_DATA_PATH="* ]]; then
-          echo "ONTOLOGIES_LINKED_DATA_PATH=$old_path"
+          echo "ONTOLOGIES_LINKED_DATA_PATH=$linked_data_path"
         elif [[ "$line" == "GOO_PATH="* ]]; then
           echo "GOO_PATH=$goo_path"
         elif [[ "$line" == "SPARQL_CLIENT_PATH="* ]]; then
@@ -74,7 +75,7 @@ create_config_files() {
 # Function to build Docker run command with conditionally added bind mounts
 build_docker_run_cmd() {
   local custom_command="$1"
-  local old_path="$2"
+  local linked_data_path="$2"
   local goo_path="$3"
   local sparql_client_path="$4"
 
@@ -82,7 +83,7 @@ build_docker_run_cmd() {
   local bash_cmd=""
 
   # Conditionally add bind mounts only if the paths are not empty
-  for path_var in "old_path:ontologies_linked_data" "goo_path:goo" "sparql_client_path:sparql-client"; do
+  for path_var in "linked_data_path:ontologies_linked_data" "goo_path:goo" "sparql_client_path:sparql-client"; do
     IFS=':' read -r path value <<< "$path_var"
 
     if [ -n "${!path}" ]; then
@@ -103,30 +104,55 @@ build_docker_run_cmd() {
 }
 
 
-provision() {
-  echo "[+] Running Cron provisioning"
+run_cron_docker_cmd() {
+  local cmd="$1"
+  echo "[+] Run: $cmd"
+  local docker_cmd="docker compose -f docker-compose.yml -p ontoportal_docker run \
+    --remove-orphans --rm --name cron-service --service-ports ncbo_cron \
+    bash -c \"$cmd\""
+
+  if ! eval "$docker_cmd"; then
+    echo "Error: Failed to run provisioning: $cmd"
+    exit 1
+  fi
+}
+
+provision_user() {
+  echo "[+] Running Cron provisioning user"
+  source .env
+
+  local commands=(
+    "bundle exec rake user:create[admin,admin@nodomain.org,password]"
+    "bundle exec rake user:adminify[admin]"
+  )
+
+  for cmd in "${commands[@]}"; do
+    run_cron_docker_cmd "$cmd"
+  done
+
+  echo "[+] Provision user setup completed successfully!"
+}
+
+provision_ontology() {
+  echo "[+] Running Cron provisioning with ontology"
   source .env
 
   echo "[+] Cleaning volumes"
   docker compose -f docker-compose.yml --profile vo down --volumes >/dev/null 2>&1
   docker compose -p ontoportal_docker down --volumes >/dev/null 2>&1
 
-  commands=(
-      "bundle exec rake user:create[admin,admin@nodomain.org,password]"
-      "bundle exec rake user:adminify[admin]"
-      "bundle exec bin/ncbo_ontology_import --admin-user admin --ontologies $STARTER_ONTOLOGY --from-apikey $OP_API_KEY --from $OP_API_URL"
-      "bundle exec bin/ncbo_ontology_process -o ${STARTER_ONTOLOGY}"
+  provision_user
+
+  local commands=(
+    "bundle exec bin/ncbo_ontology_import --admin-user admin --ontologies $STARTER_ONTOLOGY --from-apikey $OP_API_KEY --from $OP_API_URL"
+    "bundle exec bin/ncbo_ontology_process -o $STARTER_ONTOLOGY"
   )
+
   for cmd in "${commands[@]}"; do
-    echo "[+] Run: $cmd"
-    docker_cron_cmd="docker compose -f docker-compose.yml -p ontoportal_docker run  --remove-orphans --rm --name cron-service  --service-ports ncbo_cron bash -c \"$cmd\"" 
-    if ! eval "$docker_cron_cmd"; then
-        echo "Error: Failed to run provisioning .  $cmd"
-        exit 1
-    fi
+    run_cron_docker_cmd "$cmd"
   done
 
-  echo "CRON Setup completed successfully!"
+  echo "[+] CRON Setup completed successfully!"
 }
 
 # Function to handle the "dev" and "test" options
@@ -135,10 +161,11 @@ run_command() {
 
   local reset_cache=false
   local api_url=""
-  local old_path=""
+  local linked_data_path=""
   local goo_path=""
   local sparql_client_path=""
-  local with_provision=""
+  local provision_user_only_arg=""
+  local provision_ontology_arg=""
 
   shift
   # Check for command line arguments
@@ -152,8 +179,8 @@ run_command() {
         api_url="$2"
         shift 2
         ;;
-      --old-path)
-        old_path="$2"
+      --linked-data-path)
+        linked_data_path="$2"
         shift 2
         ;;
       --goo-path)
@@ -164,8 +191,12 @@ run_command() {
         sparql_client_path="$2"
         shift 2
         ;;
-      --with-provision)
-        with_provision="$1"
+      --provision-user-only)
+        provision_user_only_arg="$1"
+        shift 1
+        ;;
+      --provision-ontology)
+        provision_ontology_arg="$1"
         shift 1
         ;;
       *)
@@ -184,14 +215,14 @@ run_command() {
   fi
 
   # Check if arguments are provided
-  update_env_file "$api_url" "$old_path" "$goo_path" "$sparql_client_path"
+  update_env_file "$api_url" "$linked_data_path" "$goo_path" "$sparql_client_path"
 
 
 
   # If no arguments, fetch values from the .env file
   source .env
   api_url="$API_URL"
-  old_path="$ONTOLOGIES_LINKED_DATA_PATH"
+  linked_data_path="$ONTOLOGIES_LINKED_DATA_PATH"
   goo_path="$GOO_PATH"
   sparql_client_path="$SPARQL_CLIENT_PATH"
 
@@ -203,15 +234,19 @@ run_command() {
 
 
   # run provision
-  if [ "$with_provision" == "--with-provision"  ]; then
-    provision
+  if [ "$provision_ontology_arg" == "--provision-ontology"  ]; then
+    provision_ontology
   else
-    echo "[+] Skipping Cron provisioning"
+    if [ "$provision_user_only_arg" == "--provision-user-only"  ]; then
+      provision_user
+    else
+      echo "[+] Skipping Cron provisioning user and ontology"
+    fi
   fi
 
   # Build the Docker run command
   echo "Run: $custom_command"
-  build_docker_run_cmd "$custom_command" "$old_path" "$goo_path" "$sparql_client_path"
+  build_docker_run_cmd "$custom_command" "$linked_data_path" "$goo_path" "$sparql_client_path"
 }
 
 # Function to handle the "dev" option
@@ -231,7 +266,7 @@ test() {
   # Check for command line arguments
   while [ "$#" -gt 0 ]; do
      case "$1" in
-         --api-url | --reset-cache | --old-path | --goo-path | --sparql-client-path)
+         --api-url | --reset-cache | --linked-data-path | --goo-path | --sparql-client-path)
           all_arguments+=("$1" "$2")
           shift 2
           ;;
