refactro ontoportal script code

diff --git a/bin/ontoportal b/bin/ontoportal
--- a/bin/ontoportal
+++ b/bin/ontoportal
@@ -3,66 +3,73 @@
 # Function to display script usage information
 show_help() {
   cat << EOL
-Usage: $0 {dev|test|run|help} [--reset-cache] [--api-url API_URL] [--linked-data-path ONTOLOGIES_LINKED_DATA_PATH] [--goo-path GOO_PATH] [--sparql-client-path SPARQL_CLIENT_PATH] [--with-provision]
-  dev            : Start the Ontoportal API development server.
-                  Example: $0 dev --api-url http://localhost:9393
-                  Use --reset-cache to remove volumes: $0 dev --reset-cache
-                  Use --provision-user-only to create admin user only without ontology parsing.
-                  Use --provision-ontology to create admin user and parse ontology for use
-  test           : Run tests. Specify either a test file or use 'all'.
-                  Example: $0 test test/controllers/test_users_controller.rb -v --name=name_of_the_test
-                  Example (run all tests): $0 test all -v
-  run            : Run a command in the Ontoportal API Docker container.
-  help           : Show this help message.
+Usage:
+  $0 <command> [options]
+Commands:
+  dev       Start the OntoPortal API development server.
+            Examples:
+              $0 dev [shotgun|rackup]
+              $0 dev --api-url http://localhost:9393
+              $0 dev --reset-cache
+              $0 dev --provision-user-only
+              $0 dev --provision-ontology
+              $0 dev --linked-data-path ONTOLOGIES_LINKED_DATA_PATH
+              $0 dev --goo-path GOO_PATH
+              $0 dev  --sparql-client-path SPARQL_CLIENT_PATH
 
-Description:
-  This script provides convenient commands for managing an Ontoportal API
-  application using Docker Compose. It includes options for starting the development server,
-  running tests, and executing commands within the Ontoportal API Docker container.
+  test      Run tests (all or a specific file).
+            Examples:
+              $0 test all -v
+              $0 test test/controllers/test_users_controller.rb -v --name=name_of_the_test
+
+  run       Run a command inside the OntoPortal API Docker container.
+  help      Show this help message.
+
+Arguments:
+  [shotgun|rackup]          Specify the server that used in the dev env (default: shotgun)
 
 Options:
-  --reset-cache                                   : Remove Docker volumes (used with 'dev').
-  --provision-user-only                           : Parse ontology for use.
-  --provision-ontology                            : Parse ontology for use.
-  --api-url API_URL                               : Specify the API URL.
-  --linked-data-path ONTOLOGIES_LINKED_DATA_PATH  : Specify the path for ontologies_linked_data.
-  --goo-path GOO_PATH                             : Specify the path for goo.
-  --sparql-client-path                            : Specify the path for sparql-client.
-  test_file | all                                 : Specify either a test file or  all the tests will be run.
-  -v                                              : Enable verbosity.
-  --name=name_of_the_test                         : Specify the name of the test.
+  --api-url URL             Set the API URL (default: http://localhost:9393).
+  --reset-cache             Remove Docker volumes (use with 'dev').
+  --provision-user-only     Create only the admin user (no ontology parsing).
+  --provision-ontology      Create admin user and parse ontology for use.
+  --linked-data-path PATH   Path for ontologies_linked_data.
+  --goo-path PATH           Path for goo.
+  --sparql-client-path PATH Path for sparql-client.
+  --name=TEST_NAME          Run only the test with the given name.
 
-Goals:
-  - Simplify common tasks related to Ontoportal API development using Docker.
-  - Provide a consistent and easy-to-use interface for common actions.
+Notes:
+  - 'dev' is for local development with Docker Compose.
+  - 'test' supports both individual test files and the 'all' shortcut.
+  - 'run' lets you execute arbitrary commands inside the container.
 EOL
 }
 
 
 # Function to update or create the .env file with API_URL
 update_env_file() {
-  # Update the .env file with the provided values
-  local api_url="$1"
-  local linked_data_path="$2"
-  local goo_path="$3"
-  local sparql_client_path="$4"
+  # Default values
+  local api_url=${api_url:-http://localhost:9393}
+  local linked_data_path=${linked_data_path:-}
+  local goo_path=${goo_path:-}
+  local sparql_client_path=${sparql_client_path:-}
 
   # Update  the .env file with the provided values
   file_content=$(<.env)
 
-  # Make changes to the variable
+  # Update .env
   while IFS= read -r line; do
-        if [[ "$line" == "API_URL="* && -n "$api_url" ]]; then
-          echo "API_URL=$api_url"
-        elif [[ "$line" == "ONTOLOGIES_LINKED_DATA_PATH="* ]]; then
-          echo "ONTOLOGIES_LINKED_DATA_PATH=$linked_data_path"
-        elif [[ "$line" == "GOO_PATH="* ]]; then
-          echo "GOO_PATH=$goo_path"
-        elif [[ "$line" == "SPARQL_CLIENT_PATH="* ]]; then
-          echo "SPARQL_CLIENT_PATH=$sparql_client_path"
-        else
-          echo "$line"
-        fi
+    if [[ "$line" == "API_URL="* ]]; then
+      echo "API_URL=$api_url"
+    elif [[ "$line" == "ONTOLOGIES_LINKED_DATA_PATH="* ]]; then
+      echo "ONTOLOGIES_LINKED_DATA_PATH=$linked_data_path"
+    elif [[ "$line" == "GOO_PATH="* ]]; then
+      echo "GOO_PATH=$goo_path"
+    elif [[ "$line" == "SPARQL_CLIENT_PATH="* ]]; then
+      echo "SPARQL_CLIENT_PATH=$sparql_client_path"
+    else
+      echo "$line"
+    fi
   done <<< "$file_content" > .env
 }
 
@@ -88,7 +95,7 @@ build_docker_run_cmd() {
 
     if [ -n "${!path}" ]; then
       host_path="$(realpath "$(dirname "${!path}")")/$value"
-      echo "Run: bundle config local.$value ${!path}"
+      echo "[+] Run: bundle config local.$value ${!path}"
       container_path="/srv/ontoportal/$value"
       docker_run_cmd+=" -v $host_path:$container_path"
       bash_cmd+="(git config --global --add safe.directory $container_path && bundle config local.$value $container_path) &&"
@@ -100,6 +107,7 @@ build_docker_run_cmd() {
   bash_cmd+=" (bundle check || bundle install || bundle update) && $custom_command"
   docker_run_cmd+=" --service-ports api bash -c \"$bash_cmd\""
 
+  echo "[+] Run docker command $docker_run_cmd"
   eval "$docker_run_cmd"
 }
 
@@ -107,12 +115,9 @@ build_docker_run_cmd() {
 run_cron_docker_cmd() {
   local cmd="$1"
   echo "[+] Run: $cmd"
-  local docker_cmd="docker compose -f docker-compose.yml -p ontoportal_docker run \
-    --remove-orphans --rm --name cron-service --service-ports ncbo_cron \
-    bash -c \"$cmd\""
-
+  local docker_cmd="docker compose -f docker-compose.yml -p ontoportal_docker run --remove-orphans --rm --name cron-service --service-ports ncbo_cron bash -c \"$cmd\""
   if ! eval "$docker_cmd"; then
-    echo "Error: Failed to run provisioning: $cmd"
+    echo "[-] Error: Failed to run provisioning: $cmd"
     exit 1
   fi
 }
@@ -200,7 +205,7 @@ run_command() {
         shift 1
         ;;
       *)
-        echo "Unknown option: $1"
+        echo "[-] Unknown option: $1"
         show_help
         exit 1
         ;;
@@ -209,7 +214,7 @@ run_command() {
 
   # Check if --reset-cache is present and execute docker compose down --volumes
   if [ "$reset_cache" = true ]; then
-    echo "Resetting cache. Running: docker compose down --volumes"
+    echo "[+] Resetting cache. Running: docker compose down --volumes"
     docker compose down --volumes
     docker compose -p ontoportal_docker down --volumes
   fi
@@ -228,7 +233,7 @@ run_command() {
 
 
   if [ -z "$api_url" ] ; then
-    echo "Error: Missing required arguments. Please provide both --api-url or update them in your .env"
+    echo "[-] Error: Missing required arguments. Please provide both --api-url or update them in your .env"
     exit 1
   fi
 
@@ -245,21 +250,44 @@ run_command() {
   fi
 
   # Build the Docker run command
-  echo "Run: $custom_command"
+  echo "[+] Run: $custom_command"
+  echo "Running server running at $api_url"
   build_docker_run_cmd "$custom_command" "$linked_data_path" "$goo_path" "$sparql_client_path"
 }
 
 # Function to handle the "dev" option
 dev() {
-  echo "Starting OntoPortal API development server..."
+  echo "[+] Starting OntoPortal API development server..."
 
-  local custom_command="bundle exec shotgun --host 0.0.0.0  --env=development --port 9393"
+  # default to shotgun if not specified
+  local server_cmd=${1:-shotgun}
+  shift || true  # drop the server arg if it was provided
+
+  local custom_command
+
+  case "$server_cmd" in
+    shotgun)
+      echo "[+] Using shotgun server"
+      custom_command="bundle exec shotgun --host 0.0.0.0 --env=development --port 9393"
+      ;;
+    rackup)
+      echo "[+] Using rackup server"
+      custom_command="bundle exec rackup --host 0.0.0.0 --env=development --port 9393"
+      ;;
+    *)
+      echo "[-] Invalid server option: $server_cmd"
+      show_help
+      exit 1
+      ;;
+  esac
+
   run_command "$custom_command" "$@"
 }
 
+
 # Function to handle the "test" option
 test() {
-  echo "Running tests..."
+  echo "[+] Running tests..."
   local test_path=""
   local test_options=""
   local all_arguments=()
@@ -282,13 +310,13 @@ test() {
   done
 
   local custom_command="bundle exec rake test TEST='$test_path' TESTOPTS='$test_options'"
-  echo "run :  $custom_command"
+  echo "[+] run :  $custom_command"
   run_command "$custom_command" "${all_arguments[@]}"
 }
 
 # Function to handle the "run" option
 run() {
-  echo "Run: $*"
+  echo "[+] Run: $*"
   docker compose run --rm -it api bash -c "$*"
 }
 
